language: rust

rust:
  - stable

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release --verbose
  - cargo test --release --verbose

addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts: vps9.upsuper.org:2222

after_success:
  - sshpass -p${SFTP_PASSWORD}
    sftp -oBatchMode=no
         -b ci/deploy.sftp
         -P ${SFTP_PORT}
         ${SFTP_USERNAME}@${SFTP_SERVER}
