language: rust

rust:
  - stable

cache: cargo

env:
  # Disable rustc info cache because it causes .rustc_info.json to keep
  # changing which destablize the cache.
  - 'CARGO_CACHE_RUSTC_INFO=0'

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release --verbose
  - cargo test --release --verbose
  - strip target/release/telegram-rustevalbot
  - cp target/release/telegram-rustevalbot /tmp/

before_cache:
  - rm -rf target/{debug,release}/telegram-rustevalbot*
  - rm -rf target/{debug,release}/telegram_rustevalbot-*
  - rm -rf target/{debug,release}/{build,.fingerprint}/telegram-rustevalbot-*
  - rm -rf target/{debug,release}/deps/telegram_rustevalbot-*
  - rm -rf target/debug/incremental

deploy:
  - provider: script
    script: cd ./ci && bash deploy.sh
    on:
      branch: master
