language: rust

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      rust: stable
      cache: cargo
    - os: osx
      rust: stable
      cache: cargo
    - os: windows
      rust: stable
      cache: cargo
    - os: linux
      rust: beta
      cache: cargo
    - os: linux
      rust: nightly

env:
  # Disable rustc info cache because it causes .rustc_info.json to keep
  # changing which destablize the cache.
  - 'CARGO_CACHE_RUSTC_INFO=0'

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release --verbose
  - cargo test --release --verbose
  - bash ci/prepare_deploy.sh

before_cache:
  - rm -rf target/{debug,release}/telegram-rustevalbot*
  - rm -rf target/{debug,release}/telegram_rustevalbot-*
  - rm -rf target/{debug,release}/{build,.fingerprint}/telegram-rustevalbot-*
  - rm -rf target/{debug,release}/deps/telegram_rustevalbot-*
  - rm -rf target/debug/incremental

deploy:
  - provider: script
    script: cd ./ci && bash deploy.sh
    # It doesn't actually matter... but it's faster this way :)
    skip_cleanup: true
    on:
      branch: master
      os: linux
      rust: stable
