language: rust

rust:
  - stable

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release --verbose
  - cargo test --release --verbose
  - cp target/release/telegram-rustevalbot /tmp/
  - rm -rf target/{debug,release}/{,lib}telegram-rustevalbot*
  - rm -rf target/{debug,release}/{build,deps,.fingerprint}/telegram-rustevalbot-*
  - rm -rf target/*/{release,debug}/.fingerprint/telegram-rustevalbot-*
  - rm -rf target/debug/incremental

after_success:
  - cat ci/server_ssh_key >> $HOME/.ssh/known_hosts
  - openssl aes-256-cbc
    -K $encrypted_782b57b1cc27_key
    -iv $encrypted_782b57b1cc27_iv
    -in ci/deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - chmod 0600 /tmp/deploy_rsa
  - sftp -i /tmp/deploy_rsa
         -b ci/deploy.sftp
         -P 2222
         rustevalbot@vps9.upsuper.org
  - rm /tmp/deploy_rsa

notifications:
  email:
    recipients:
      - travis-ci@upsuper.org
    on_success: always
