language: rust

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      rust: stable
    - os: osx
      rust: stable
    - os: windows
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly

cache: cargo

env:
  # Disable rustc info cache because it causes .rustc_info.json to keep
  # changing which destablize the cache.
  - 'CARGO_CACHE_RUSTC_INFO=0'

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release --verbose
  - cargo test --release --verbose
  - bash ci/prepare_deploy.sh

before_cache:
  - bash ci/cleanup_for_cache.sh

deploy:
  - provider: script
    script: cd ./ci && bash deploy.sh
    # It doesn't actually matter... but it's faster this way :)
    skip_cleanup: true
    on:
      branch: master
      rust: stable
      condition: "$TRAVIS_OS_NAME" == "linux"
