[package]
name = "telegram-rustevalbot"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]
license = "MIT"
homepage = "https://github.com/upsuper/telegram-rustevalbot"

[dependencies]
dotenv = "0.13"
env_logger = "0.5"
fst = "0.3"
fst-subseq-ascii-caseless = "0.1"
futures = "0.1"
htmlescape = "0.3"
itertools = "0.7"
lazy_static = "1.1"
log = "0.4"
matches = "0.1"
notify = "4.0"
percent-encoding = "1.0"
regex = "1.0"
reqwest = { version = "0.8", features = ["unstable"] }
rustdoc-seeker = "0.5.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
telegram-bot = "0.6"
tokio-core = "0.1"
unicode-width = "0.1"

[build-dependencies]
git-version = "0.2"

[dev-dependencies]
string_cache = "0.7"
