[package]
name = "telegram-rustevalbot"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]
license = "MIT"
homepage = "https://github.com/upsuper/telegram-rustevalbot"

[dependencies]
htmlescape = "0.3"
itertools = "0.7"
futures = "0.1"
lazy_static = "1.1"
matches = "0.1"
percent-encoding = "1.0"
regex = "1.0"
reqwest = { version = "0.8", features = ["unstable"] }
serde = "1.0"
serde_derive = "1.0"
telegram-bot = "0.6"
tokio-core = "0.1"

[build-dependencies]
git-version = "0.2"
